### ISSUE TITLE
[Suggestion] Possible 'Gold Dragon-ify' function?

### ISSUE THREAD

**Issue by Crunklio** [alterasc/MythicPathPowerSwapper#1]
Since Gold Dragon (seemingly) has pre-ML8 progression, would it be possible to add Gold Dragon swap support, maintaining the base path's spellbook if feasible?

**Comment by alterasc** [comment]
I toyed with the idea of making GD-ify option that stretches GD progression from MR8..10 to MR3..10 (with abilities scaling form MR, similar to Legendarify)

But don't know if I ever get to it.
