### ISSUE TITLE
Trully swap instead of rewrite

### ISSUE THREAD

**Issue by aguile** [alterasc/MythicPathPowerSwapper#2]
As it is right now, the mod pretty much copies the mythic path abilities and spells from a source to a target. Instead of truly swapping, it pretty much duplicates everything on another mythic class slot. Ex: Swapping Angel for Demon, leaves yout with 2x demon paths and no Angel on the list.

With the new toybox update, it has now an option for you to add mythic classes to your companion, but using this mod leaves you with one less unique mythic path available on the list. Like on the example above, I am unable to choose angel to one of my companions at since it has been overwritten by the demon path abilities

My suggestion is to make it truly swap the mythic classes. Again on with the same example in mind, make the Demon path powers available as Angel and Angel path powers available on the Demon slot as well. This way we could still the mythic path we swapped with our companions using the Toybox mod,

**Comment by alterasc** [comment]
Copying my response from Nexus:

Unfortunately not happening for couple of reasons.
1. Yes, it does only A <- B transition and not A <-> B, but that has the benefit of not affecting games where you play path B as normal. At least almost.
2. Full swap brings nothing for normal games, where only MC is supposed to have one set of mythic powers. While trying to support Toybox things would just add huge amount of work to me that honestly I'm not interested in (especially as I don't use Toybox myself).
